# Generated by Django 4.2.1 on 2023-06-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Json_Web_Token', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Student_data',
        ),
    ]
